require 'eBay.rb'
require 'eBayMappingRegistry.rb'
require 'soap/rpc/driver'

class EBayAPIInterface < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "https://api.ebay.com/wsapi"

  Methods = [
    [ "",
      "addDispute",
      [ ["in", "AddDisputeRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddDisputeRequest"]],
        ["out", "AddDisputeResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddDisputeResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "addDisputeResponse",
      [ ["in", "AddDisputeResponseRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddDisputeResponseRequest"]],
        ["out", "AddDisputeResponseResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddDisputeResponseResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "addItem",
      [ ["in", "AddItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddItemRequest"]],
        ["out", "AddItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddItemResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "addLiveAuctionItem",
      [ ["in", "AddLiveAuctionItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddLiveAuctionItemRequest"]],
        ["out", "AddLiveAuctionItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddLiveAuctionItemResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "addMemberMessageAAQToPartner",
      [ ["in", "AddMemberMessageAAQToPartnerRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddMemberMessageAAQToPartnerRequest"]],
        ["out", "AddMemberMessageAAQToPartnerResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddMemberMessageAAQToPartnerResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "addMemberMessageRTQ",
      [ ["in", "AddMemberMessageRTQRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddMemberMessageRTQRequest"]],
        ["out", "AddMemberMessageRTQResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddMemberMessageRTQResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "addMemberMessagesAAQToBidder",
      [ ["in", "AddMemberMessagesAAQToBidderRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddMemberMessagesAAQToBidderRequest"]],
        ["out", "AddMemberMessagesAAQToBidderResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddMemberMessagesAAQToBidderResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "addOrder",
      [ ["in", "AddOrderRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddOrderRequest"]],
        ["out", "AddOrderResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddOrderResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "addSecondChanceItem",
      [ ["in", "AddSecondChanceItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddSecondChanceItemRequest"]],
        ["out", "AddSecondChanceItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddSecondChanceItemResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "addToItemDescription",
      [ ["in", "AddToItemDescriptionRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddToItemDescriptionRequest"]],
        ["out", "AddToItemDescriptionResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddToItemDescriptionResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "addToWatchList",
      [ ["in", "AddToWatchListRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddToWatchListRequest"]],
        ["out", "AddToWatchListResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddToWatchListResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "addTransactionConfirmationItem",
      [ ["in", "AddTransactionConfirmationItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddTransactionConfirmationItemRequest"]],
        ["out", "AddTransactionConfirmationItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddTransactionConfirmationItemResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "approveLiveAuctionBidders",
      [ ["in", "ApproveLiveAuctionBiddersRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ApproveLiveAuctionBiddersRequest"]],
        ["out", "ApproveLiveAuctionBiddersResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ApproveLiveAuctionBiddersResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "completeSale",
      [ ["in", "CompleteSaleRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "CompleteSaleRequest"]],
        ["out", "CompleteSaleResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "CompleteSaleResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "confirmIdentity",
      [ ["in", "ConfirmIdentityRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ConfirmIdentityRequest"]],
        ["out", "ConfirmIdentityResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ConfirmIdentityResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "deleteMyMessages",
      [ ["in", "DeleteMyMessagesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "DeleteMyMessagesRequest"]],
        ["out", "DeleteMyMessagesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "DeleteMyMessagesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "endItem",
      [ ["in", "EndItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "EndItemRequest"]],
        ["out", "EndItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "EndItemResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "fetchToken",
      [ ["in", "FetchTokenRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "FetchTokenRequest"]],
        ["out", "FetchTokenResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "FetchTokenResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getAccount",
      [ ["in", "GetAccountRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAccountRequest"]],
        ["out", "GetAccountResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAccountResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getAdFormatLeads",
      [ ["in", "GetAdFormatLeadsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAdFormatLeadsRequest"]],
        ["out", "GetAdFormatLeadsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAdFormatLeadsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getAllBidders",
      [ ["in", "GetAllBiddersRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAllBiddersRequest"]],
        ["out", "GetAllBiddersResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAllBiddersResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getApiAccessRules",
      [ ["in", "GetApiAccessRulesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetApiAccessRulesRequest"]],
        ["out", "GetApiAccessRulesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetApiAccessRulesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getAttributesCS",
      [ ["in", "GetAttributesCSRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAttributesCSRequest"]],
        ["out", "GetAttributesCSResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAttributesCSResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getAttributesXSL",
      [ ["in", "GetAttributesXSLRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAttributesXSLRequest"]],
        ["out", "GetAttributesXSLResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAttributesXSLResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getBestOffers",
      [ ["in", "GetBestOffersRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetBestOffersRequest"]],
        ["out", "GetBestOffersResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetBestOffersResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getBidderList",
      [ ["in", "GetBidderListRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetBidderListRequest"]],
        ["out", "GetBidderListResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetBidderListResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getCategories",
      [ ["in", "GetCategoriesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategoriesRequest"]],
        ["out", "GetCategoriesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategoriesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getCategory2CS",
      [ ["in", "GetCategory2CSRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategory2CSRequest"]],
        ["out", "GetCategory2CSResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategory2CSResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getCategoryFeatures",
      [ ["in", "GetCategoryFeaturesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategoryFeaturesRequest"]],
        ["out", "GetCategoryFeaturesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategoryFeaturesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getCategoryListings",
      [ ["in", "GetCategoryListingsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategoryListingsRequest"]],
        ["out", "GetCategoryListingsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategoryListingsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getCategoryMappings",
      [ ["in", "GetCategoryMappingsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategoryMappingsRequest"]],
        ["out", "GetCategoryMappingsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategoryMappingsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getCategorySpecifics",
      [ ["in", "GetCategorySpecificsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategorySpecificsRequest"]],
        ["out", "GetCategorySpecificsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategorySpecificsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getChallengeToken",
      [ ["in", "GetChallengeTokenRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetChallengeTokenRequest"]],
        ["out", "GetChallengeTokenResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetChallengeTokenResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getCharities",
      [ ["in", "GetCharitiesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCharitiesRequest"]],
        ["out", "GetCharitiesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCharitiesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getClientAlertsAuthToken",
      [ ["in", "GetClientAlertsAuthTokenRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetClientAlertsAuthTokenRequest"]],
        ["out", "GetClientAlertsAuthTokenResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetClientAlertsAuthTokenResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getContextualKeywords",
      [ ["in", "GetContextualKeywordsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetContextualKeywordsRequest"]],
        ["out", "GetContextualKeywordsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetContextualKeywordsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getCrossPromotions",
      [ ["in", "GetCrossPromotionsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCrossPromotionsRequest"]],
        ["out", "GetCrossPromotionsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCrossPromotionsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getDescriptionTemplates",
      [ ["in", "GetDescriptionTemplatesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetDescriptionTemplatesRequest"]],
        ["out", "GetDescriptionTemplatesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetDescriptionTemplatesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getDispute",
      [ ["in", "GetDisputeRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetDisputeRequest"]],
        ["out", "GetDisputeResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetDisputeResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getFeedback",
      [ ["in", "GetFeedbackRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetFeedbackRequest"]],
        ["out", "GetFeedbackResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetFeedbackResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getHighBidders",
      [ ["in", "GetHighBiddersRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetHighBiddersRequest"]],
        ["out", "GetHighBiddersResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetHighBiddersResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getItem",
      [ ["in", "GetItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemRequest"]],
        ["out", "GetItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getItemRecommendations",
      [ ["in", "GetItemRecommendationsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemRecommendationsRequest"]],
        ["out", "GetItemRecommendationsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemRecommendationsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getItemShipping",
      [ ["in", "GetItemShippingRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemShippingRequest"]],
        ["out", "GetItemShippingResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemShippingResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getItemTransactions",
      [ ["in", "GetItemTransactionsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemTransactionsRequest"]],
        ["out", "GetItemTransactionsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemTransactionsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getItemsAwaitingFeedback",
      [ ["in", "GetItemsAwaitingFeedbackRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemsAwaitingFeedbackRequest"]],
        ["out", "GetItemsAwaitingFeedbackResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemsAwaitingFeedbackResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getLiveAuctionBidders",
      [ ["in", "GetLiveAuctionBiddersRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetLiveAuctionBiddersRequest"]],
        ["out", "GetLiveAuctionBiddersResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetLiveAuctionBiddersResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getLiveAuctionCatalogDetails",
      [ ["in", "GetLiveAuctionCatalogDetailsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetLiveAuctionCatalogDetailsRequest"]],
        ["out", "GetLiveAuctionCatalogDetailsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetLiveAuctionCatalogDetailsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getMemberMessages",
      [ ["in", "GetMemberMessagesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMemberMessagesRequest"]],
        ["out", "GetMemberMessagesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMemberMessagesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getMessagePreferences",
      [ ["in", "GetMessagePreferencesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMessagePreferencesRequest"]],
        ["out", "GetMessagePreferencesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMessagePreferencesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getMyMessages",
      [ ["in", "GetMyMessagesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyMessagesRequest"]],
        ["out", "GetMyMessagesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyMessagesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getMyeBayBuying",
      [ ["in", "GetMyeBayBuyingRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyeBayBuyingRequest"]],
        ["out", "GetMyeBayBuyingResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyeBayBuyingResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getMyeBayReminders",
      [ ["in", "GetMyeBayRemindersRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyeBayRemindersRequest"]],
        ["out", "GetMyeBayRemindersResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyeBayRemindersResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getMyeBaySelling",
      [ ["in", "GetMyeBaySellingRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyeBaySellingRequest"]],
        ["out", "GetMyeBaySellingResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyeBaySellingResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getNotificationPreferences",
      [ ["in", "GetNotificationPreferencesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetNotificationPreferencesRequest"]],
        ["out", "GetNotificationPreferencesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetNotificationPreferencesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getNotificationsUsage",
      [ ["in", "GetNotificationsUsageRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetNotificationsUsageRequest"]],
        ["out", "GetNotificationsUsageResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetNotificationsUsageResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getOrderTransactions",
      [ ["in", "GetOrderTransactionsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetOrderTransactionsRequest"]],
        ["out", "GetOrderTransactionsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetOrderTransactionsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getOrders",
      [ ["in", "GetOrdersRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetOrdersRequest"]],
        ["out", "GetOrdersResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetOrdersResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getPictureManagerDetails",
      [ ["in", "GetPictureManagerDetailsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPictureManagerDetailsRequest"]],
        ["out", "GetPictureManagerDetailsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPictureManagerDetailsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getPictureManagerOptions",
      [ ["in", "GetPictureManagerOptionsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPictureManagerOptionsRequest"]],
        ["out", "GetPictureManagerOptionsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPictureManagerOptionsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getPopularKeywords",
      [ ["in", "GetPopularKeywordsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPopularKeywordsRequest"]],
        ["out", "GetPopularKeywordsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPopularKeywordsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getProductFamilyMembers",
      [ ["in", "GetProductFamilyMembersRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductFamilyMembersRequest"]],
        ["out", "GetProductFamilyMembersResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductFamilyMembersResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getProductFinder",
      [ ["in", "GetProductFinderRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductFinderRequest"]],
        ["out", "GetProductFinderResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductFinderResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getProductFinderXSL",
      [ ["in", "GetProductFinderXSLRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductFinderXSLRequest"]],
        ["out", "GetProductFinderXSLResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductFinderXSLResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getProductSearchPage",
      [ ["in", "GetProductSearchPageRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductSearchPageRequest"]],
        ["out", "GetProductSearchPageResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductSearchPageResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getProductSearchResults",
      [ ["in", "GetProductSearchResultsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductSearchResultsRequest"]],
        ["out", "GetProductSearchResultsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductSearchResultsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getProductSellingPages",
      [ ["in", "GetProductSellingPagesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductSellingPagesRequest"]],
        ["out", "GetProductSellingPagesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductSellingPagesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getProducts",
      [ ["in", "GetProductsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductsRequest"]],
        ["out", "GetProductsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getPromotionRules",
      [ ["in", "GetPromotionRulesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPromotionRulesRequest"]],
        ["out", "GetPromotionRulesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPromotionRulesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getPromotionalSaleDetails",
      [ ["in", "GetPromotionalSaleDetailsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPromotionalSaleDetailsRequest"]],
        ["out", "GetPromotionalSaleDetailsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPromotionalSaleDetailsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getSearchResults",
      [ ["in", "GetSearchResultsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSearchResultsRequest"]],
        ["out", "GetSearchResultsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSearchResultsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getSellerDashboard",
      [ ["in", "GetSellerDashboardRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerDashboardRequest"]],
        ["out", "GetSellerDashboardResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerDashboardResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getSellerEvents",
      [ ["in", "GetSellerEventsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerEventsRequest"]],
        ["out", "GetSellerEventsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerEventsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getSellerList",
      [ ["in", "GetSellerListRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerListRequest"]],
        ["out", "GetSellerListResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerListResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getSellerPayments",
      [ ["in", "GetSellerPaymentsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerPaymentsRequest"]],
        ["out", "GetSellerPaymentsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerPaymentsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getSellerTransactions",
      [ ["in", "GetSellerTransactionsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerTransactionsRequest"]],
        ["out", "GetSellerTransactionsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerTransactionsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getSessionID",
      [ ["in", "GetSessionIDRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSessionIDRequest"]],
        ["out", "GetSessionIDResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSessionIDResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getShippingDiscountProfiles",
      [ ["in", "GetShippingDiscountProfilesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetShippingDiscountProfilesRequest"]],
        ["out", "GetShippingDiscountProfilesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetShippingDiscountProfilesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getStore",
      [ ["in", "GetStoreRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStoreRequest"]],
        ["out", "GetStoreResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStoreResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getStoreCategoryUpdateStatus",
      [ ["in", "GetStoreCategoryUpdateStatusRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStoreCategoryUpdateStatusRequest"]],
        ["out", "GetStoreCategoryUpdateStatusResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStoreCategoryUpdateStatusResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getStoreCustomPage",
      [ ["in", "GetStoreCustomPageRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStoreCustomPageRequest"]],
        ["out", "GetStoreCustomPageResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStoreCustomPageResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getStoreOptions",
      [ ["in", "GetStoreOptionsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStoreOptionsRequest"]],
        ["out", "GetStoreOptionsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStoreOptionsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getStorePreferences",
      [ ["in", "GetStorePreferencesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStorePreferencesRequest"]],
        ["out", "GetStorePreferencesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStorePreferencesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getSuggestedCategories",
      [ ["in", "GetSuggestedCategoriesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSuggestedCategoriesRequest"]],
        ["out", "GetSuggestedCategoriesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSuggestedCategoriesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getTaxTable",
      [ ["in", "GetTaxTableRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetTaxTableRequest"]],
        ["out", "GetTaxTableResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetTaxTableResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getTokenStatus",
      [ ["in", "GetTokenStatusRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetTokenStatusRequest"]],
        ["out", "GetTokenStatusResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetTokenStatusResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getUser",
      [ ["in", "GetUserRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetUserRequest"]],
        ["out", "GetUserResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetUserResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getUserContactDetails",
      [ ["in", "GetUserContactDetailsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetUserContactDetailsRequest"]],
        ["out", "GetUserContactDetailsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetUserContactDetailsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getUserDisputes",
      [ ["in", "GetUserDisputesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetUserDisputesRequest"]],
        ["out", "GetUserDisputesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetUserDisputesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getUserPreferences",
      [ ["in", "GetUserPreferencesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetUserPreferencesRequest"]],
        ["out", "GetUserPreferencesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetUserPreferencesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getVeROReasonCodeDetails",
      [ ["in", "GetVeROReasonCodeDetailsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetVeROReasonCodeDetailsRequest"]],
        ["out", "GetVeROReasonCodeDetailsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetVeROReasonCodeDetailsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getVeROReportStatus",
      [ ["in", "GetVeROReportStatusRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetVeROReportStatusRequest"]],
        ["out", "GetVeROReportStatusResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetVeROReportStatusResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getWantItNowPost",
      [ ["in", "GetWantItNowPostRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetWantItNowPostRequest"]],
        ["out", "GetWantItNowPostResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetWantItNowPostResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "getWantItNowSearchResults",
      [ ["in", "GetWantItNowSearchResultsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetWantItNowSearchResultsRequest"]],
        ["out", "GetWantItNowSearchResultsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetWantItNowSearchResultsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "geteBayDetails",
      [ ["in", "GeteBayDetailsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GeteBayDetailsRequest"]],
        ["out", "GeteBayDetailsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GeteBayDetailsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "geteBayOfficialTime",
      [ ["in", "GeteBayOfficialTimeRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GeteBayOfficialTimeRequest"]],
        ["out", "GeteBayOfficialTimeResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GeteBayOfficialTimeResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "issueRefund",
      [ ["in", "IssueRefundRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "IssueRefundRequest"]],
        ["out", "IssueRefundResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "IssueRefundResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "leaveFeedback",
      [ ["in", "LeaveFeedbackRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "LeaveFeedbackRequest"]],
        ["out", "LeaveFeedbackResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "LeaveFeedbackResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "placeOffer",
      [ ["in", "PlaceOfferRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "PlaceOfferRequest"]],
        ["out", "PlaceOfferResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "PlaceOfferResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "relistItem",
      [ ["in", "RelistItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RelistItemRequest"]],
        ["out", "RelistItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RelistItemResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "removeFromWatchList",
      [ ["in", "RemoveFromWatchListRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RemoveFromWatchListRequest"]],
        ["out", "RemoveFromWatchListResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RemoveFromWatchListResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "respondToBestOffer",
      [ ["in", "RespondToBestOfferRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RespondToBestOfferRequest"]],
        ["out", "RespondToBestOfferResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RespondToBestOfferResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "respondToFeedback",
      [ ["in", "RespondToFeedbackRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RespondToFeedbackRequest"]],
        ["out", "RespondToFeedbackResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RespondToFeedbackResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "respondToWantItNowPost",
      [ ["in", "RespondToWantItNowPostRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RespondToWantItNowPostRequest"]],
        ["out", "RespondToWantItNowPostResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RespondToWantItNowPostResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "reviseCheckoutStatus",
      [ ["in", "ReviseCheckoutStatusRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseCheckoutStatusRequest"]],
        ["out", "ReviseCheckoutStatusResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseCheckoutStatusResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "reviseItem",
      [ ["in", "ReviseItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseItemRequest"]],
        ["out", "ReviseItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseItemResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "reviseLiveAuctionItem",
      [ ["in", "ReviseLiveAuctionItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseLiveAuctionItemRequest"]],
        ["out", "ReviseLiveAuctionItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseLiveAuctionItemResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "reviseMyMessages",
      [ ["in", "ReviseMyMessagesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseMyMessagesRequest"]],
        ["out", "ReviseMyMessagesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseMyMessagesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "reviseMyMessagesFolders",
      [ ["in", "ReviseMyMessagesFoldersRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseMyMessagesFoldersRequest"]],
        ["out", "ReviseMyMessagesFoldersResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseMyMessagesFoldersResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "revokeToken",
      [ ["in", "RevokeTokenRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RevokeTokenRequest"]],
        ["out", "RevokeTokenResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RevokeTokenResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "sellerReverseDispute",
      [ ["in", "SellerReverseDisputeRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SellerReverseDisputeRequest"]],
        ["out", "SellerReverseDisputeResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SellerReverseDisputeResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "sendInvoice",
      [ ["in", "SendInvoiceRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SendInvoiceRequest"]],
        ["out", "SendInvoiceResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SendInvoiceResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "setMessagePreferences",
      [ ["in", "SetMessagePreferencesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetMessagePreferencesRequest"]],
        ["out", "SetMessagePreferencesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetMessagePreferencesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "setNotificationPreferences",
      [ ["in", "SetNotificationPreferencesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetNotificationPreferencesRequest"]],
        ["out", "SetNotificationPreferencesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetNotificationPreferencesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "setPictureManagerDetails",
      [ ["in", "SetPictureManagerDetailsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetPictureManagerDetailsRequest"]],
        ["out", "SetPictureManagerDetailsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetPictureManagerDetailsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "setPromotionalSale",
      [ ["in", "SetPromotionalSaleRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetPromotionalSaleRequest"]],
        ["out", "SetPromotionalSaleResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetPromotionalSaleResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "setPromotionalSaleListings",
      [ ["in", "SetPromotionalSaleListingsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetPromotionalSaleListingsRequest"]],
        ["out", "SetPromotionalSaleListingsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetPromotionalSaleListingsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "setSellingManagerFeedbackOptions",
      [ ["in", "SetSellingManagerFeedbackOptionsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetSellingManagerFeedbackOptionsRequest"]],
        ["out", "SetSellingManagerFeedbackOptionsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetSellingManagerFeedbackOptionsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "setShippingDiscountProfiles",
      [ ["in", "SetShippingDiscountProfilesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetShippingDiscountProfilesRequest"]],
        ["out", "SetShippingDiscountProfilesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetShippingDiscountProfilesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "setStore",
      [ ["in", "SetStoreRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetStoreRequest"]],
        ["out", "SetStoreResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetStoreResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "setStoreCategories",
      [ ["in", "SetStoreCategoriesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetStoreCategoriesRequest"]],
        ["out", "SetStoreCategoriesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetStoreCategoriesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "setStoreCustomPage",
      [ ["in", "SetStoreCustomPageRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetStoreCustomPageRequest"]],
        ["out", "SetStoreCustomPageResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetStoreCustomPageResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "setStorePreferences",
      [ ["in", "SetStorePreferencesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetStorePreferencesRequest"]],
        ["out", "SetStorePreferencesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetStorePreferencesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "setTaxTable",
      [ ["in", "SetTaxTableRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetTaxTableRequest"]],
        ["out", "SetTaxTableResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetTaxTableResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "setUserNotes",
      [ ["in", "SetUserNotesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetUserNotesRequest"]],
        ["out", "SetUserNotesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetUserNotesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "setUserPreferences",
      [ ["in", "SetUserPreferencesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetUserPreferencesRequest"]],
        ["out", "SetUserPreferencesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetUserPreferencesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "uploadSiteHostedPictures",
      [ ["in", "UploadSiteHostedPicturesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "UploadSiteHostedPicturesRequest"]],
        ["out", "UploadSiteHostedPicturesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "UploadSiteHostedPicturesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "validateChallengeInput",
      [ ["in", "ValidateChallengeInputRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ValidateChallengeInputRequest"]],
        ["out", "ValidateChallengeInputResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ValidateChallengeInputResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "validateTestUserRegistration",
      [ ["in", "ValidateTestUserRegistrationRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ValidateTestUserRegistrationRequest"]],
        ["out", "ValidateTestUserRegistrationResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ValidateTestUserRegistrationResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "veROReportItems",
      [ ["in", "VeROReportItemsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "VeROReportItemsRequest"]],
        ["out", "VeROReportItemsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "VeROReportItemsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "verifyAddItem",
      [ ["in", "VerifyAddItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "VerifyAddItemRequest"]],
        ["out", "VerifyAddItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "VerifyAddItemResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "verifyAddSecondChanceItem",
      [ ["in", "VerifyAddSecondChanceItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "VerifyAddSecondChanceItemRequest"]],
        ["out", "VerifyAddSecondChanceItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "VerifyAddSecondChanceItemResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = DefaultMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = DefaultMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end

