require 'eBay.rb'
require 'soap/rpc/driver'

class EBayAPIInterface < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "https://api.ebay.com/wsapi"
  MappingRegistry = ::SOAP::Mapping::Registry.new

  Methods = [
    [ "",
      "addDispute",
      [ ["in", "AddDisputeRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddDisputeRequest"], true],
        ["out", "AddDisputeResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddDisputeResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "addDisputeResponse",
      [ ["in", "AddDisputeResponseRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddDisputeResponseRequest"], true],
        ["out", "AddDisputeResponseResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddDisputeResponseResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "addItem",
      [ ["in", "AddItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddItemRequest"], true],
        ["out", "AddItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddItemResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "addLiveAuctionItem",
      [ ["in", "AddLiveAuctionItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddLiveAuctionItemRequest"], true],
        ["out", "AddLiveAuctionItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddLiveAuctionItemResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "addMemberMessage",
      [ ["in", "AddMemberMessageRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddMemberMessageRequest"], true],
        ["out", "AddMemberMessageResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddMemberMessageResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "addOrder",
      [ ["in", "AddOrderRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddOrderRequest"], true],
        ["out", "AddOrderResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddOrderResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "addSecondChanceItem",
      [ ["in", "AddSecondChanceItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddSecondChanceItemRequest"], true],
        ["out", "AddSecondChanceItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddSecondChanceItemResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "addToItemDescription",
      [ ["in", "AddToItemDescriptionRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddToItemDescriptionRequest"], true],
        ["out", "AddToItemDescriptionResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddToItemDescriptionResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "addToWatchList",
      [ ["in", "AddToWatchListRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddToWatchListRequest"], true],
        ["out", "AddToWatchListResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "AddToWatchListResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "completeSale",
      [ ["in", "CompleteSaleRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "CompleteSaleRequest"], true],
        ["out", "CompleteSaleResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "CompleteSaleResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "deleteMyMessages",
      [ ["in", "DeleteMyMessagesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "DeleteMyMessagesRequest"], true],
        ["out", "DeleteMyMessagesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "DeleteMyMessagesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "endItem",
      [ ["in", "EndItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "EndItemRequest"], true],
        ["out", "EndItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "EndItemResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "fetchToken",
      [ ["in", "FetchTokenRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "FetchTokenRequest"], true],
        ["out", "FetchTokenResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "FetchTokenResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getAccount",
      [ ["in", "GetAccountRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAccountRequest"], true],
        ["out", "GetAccountResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAccountResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getAdFormatLeads",
      [ ["in", "GetAdFormatLeadsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAdFormatLeadsRequest"], true],
        ["out", "GetAdFormatLeadsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAdFormatLeadsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getAllBidders",
      [ ["in", "GetAllBiddersRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAllBiddersRequest"], true],
        ["out", "GetAllBiddersResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAllBiddersResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getApiAccessRules",
      [ ["in", "GetApiAccessRulesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetApiAccessRulesRequest"], true],
        ["out", "GetApiAccessRulesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetApiAccessRulesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getAttributesCS",
      [ ["in", "GetAttributesCSRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAttributesCSRequest"], true],
        ["out", "GetAttributesCSResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAttributesCSResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getAttributesXSL",
      [ ["in", "GetAttributesXSLRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAttributesXSLRequest"], true],
        ["out", "GetAttributesXSLResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetAttributesXSLResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getBestOffers",
      [ ["in", "GetBestOffersRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetBestOffersRequest"], true],
        ["out", "GetBestOffersResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetBestOffersResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getBidderList",
      [ ["in", "GetBidderListRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetBidderListRequest"], true],
        ["out", "GetBidderListResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetBidderListResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getCategories",
      [ ["in", "GetCategoriesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategoriesRequest"], true],
        ["out", "GetCategoriesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategoriesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getCategory2CS",
      [ ["in", "GetCategory2CSRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategory2CSRequest"], true],
        ["out", "GetCategory2CSResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategory2CSResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getCategory2FinanceOffer",
      [ ["in", "GetCategory2FinanceOfferRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategory2FinanceOfferRequest"], true],
        ["out", "GetCategory2FinanceOfferResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategory2FinanceOfferResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getCategoryFeatures",
      [ ["in", "GetCategoryFeaturesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategoryFeaturesRequest"], true],
        ["out", "GetCategoryFeaturesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategoryFeaturesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getCategoryListings",
      [ ["in", "GetCategoryListingsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategoryListingsRequest"], true],
        ["out", "GetCategoryListingsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategoryListingsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getCategoryMappings",
      [ ["in", "GetCategoryMappingsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategoryMappingsRequest"], true],
        ["out", "GetCategoryMappingsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCategoryMappingsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getCharities",
      [ ["in", "GetCharitiesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCharitiesRequest"], true],
        ["out", "GetCharitiesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCharitiesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getCrossPromotions",
      [ ["in", "GetCrossPromotionsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCrossPromotionsRequest"], true],
        ["out", "GetCrossPromotionsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetCrossPromotionsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getDescriptionTemplates",
      [ ["in", "GetDescriptionTemplatesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetDescriptionTemplatesRequest"], true],
        ["out", "GetDescriptionTemplatesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetDescriptionTemplatesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getDispute",
      [ ["in", "GetDisputeRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetDisputeRequest"], true],
        ["out", "GetDisputeResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetDisputeResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getFeedback",
      [ ["in", "GetFeedbackRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetFeedbackRequest"], true],
        ["out", "GetFeedbackResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetFeedbackResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getFinanceOffers",
      [ ["in", "GetFinanceOffersRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetFinanceOffersRequest"], true],
        ["out", "GetFinanceOffersResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetFinanceOffersResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getHighBidders",
      [ ["in", "GetHighBiddersRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetHighBiddersRequest"], true],
        ["out", "GetHighBiddersResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetHighBiddersResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getItem",
      [ ["in", "GetItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemRequest"], true],
        ["out", "GetItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getItemRecommendations",
      [ ["in", "GetItemRecommendationsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemRecommendationsRequest"], true],
        ["out", "GetItemRecommendationsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemRecommendationsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getItemShipping",
      [ ["in", "GetItemShippingRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemShippingRequest"], true],
        ["out", "GetItemShippingResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemShippingResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getItemTransactions",
      [ ["in", "GetItemTransactionsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemTransactionsRequest"], true],
        ["out", "GetItemTransactionsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemTransactionsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getItemsAwaitingFeedback",
      [ ["in", "GetItemsAwaitingFeedbackRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemsAwaitingFeedbackRequest"], true],
        ["out", "GetItemsAwaitingFeedbackResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetItemsAwaitingFeedbackResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getLiveAuctionCatalogDetails",
      [ ["in", "GetLiveAuctionCatalogDetailsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetLiveAuctionCatalogDetailsRequest"], true],
        ["out", "GetLiveAuctionCatalogDetailsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetLiveAuctionCatalogDetailsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getMemberMessages",
      [ ["in", "GetMemberMessagesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMemberMessagesRequest"], true],
        ["out", "GetMemberMessagesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMemberMessagesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getMyMessages",
      [ ["in", "GetMyMessagesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyMessagesRequest"], true],
        ["out", "GetMyMessagesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyMessagesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getMyeBay",
      [ ["in", "GetMyeBayRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyeBayRequest"], true],
        ["out", "GetMyeBayResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyeBayResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getMyeBayBuying",
      [ ["in", "GetMyeBayBuyingRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyeBayBuyingRequest"], true],
        ["out", "GetMyeBayBuyingResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyeBayBuyingResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getMyeBayReminders",
      [ ["in", "GetMyeBayRemindersRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyeBayRemindersRequest"], true],
        ["out", "GetMyeBayRemindersResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyeBayRemindersResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getMyeBaySelling",
      [ ["in", "GetMyeBaySellingRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyeBaySellingRequest"], true],
        ["out", "GetMyeBaySellingResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetMyeBaySellingResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getNotificationPreferences",
      [ ["in", "GetNotificationPreferencesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetNotificationPreferencesRequest"], true],
        ["out", "GetNotificationPreferencesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetNotificationPreferencesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getOrders",
      [ ["in", "GetOrdersRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetOrdersRequest"], true],
        ["out", "GetOrdersResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetOrdersResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getPictureManagerDetails",
      [ ["in", "GetPictureManagerDetailsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPictureManagerDetailsRequest"], true],
        ["out", "GetPictureManagerDetailsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPictureManagerDetailsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getPictureManagerOptions",
      [ ["in", "GetPictureManagerOptionsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPictureManagerOptionsRequest"], true],
        ["out", "GetPictureManagerOptionsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPictureManagerOptionsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getPopularKeywords",
      [ ["in", "GetPopularKeywordsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPopularKeywordsRequest"], true],
        ["out", "GetPopularKeywordsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPopularKeywordsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getProductFamilyMembers",
      [ ["in", "GetProductFamilyMembersRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductFamilyMembersRequest"], true],
        ["out", "GetProductFamilyMembersResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductFamilyMembersResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getProductFinder",
      [ ["in", "GetProductFinderRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductFinderRequest"], true],
        ["out", "GetProductFinderResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductFinderResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getProductFinderXSL",
      [ ["in", "GetProductFinderXSLRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductFinderXSLRequest"], true],
        ["out", "GetProductFinderXSLResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductFinderXSLResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getProductSearchPage",
      [ ["in", "GetProductSearchPageRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductSearchPageRequest"], true],
        ["out", "GetProductSearchPageResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductSearchPageResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getProductSearchResults",
      [ ["in", "GetProductSearchResultsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductSearchResultsRequest"], true],
        ["out", "GetProductSearchResultsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductSearchResultsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getProductSellingPages",
      [ ["in", "GetProductSellingPagesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductSellingPagesRequest"], true],
        ["out", "GetProductSellingPagesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetProductSellingPagesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getPromotionRules",
      [ ["in", "GetPromotionRulesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPromotionRulesRequest"], true],
        ["out", "GetPromotionRulesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetPromotionRulesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getRecommendations",
      [ ["in", "GetRecommendationsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetRecommendationsRequest"], true],
        ["out", "GetRecommendationsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetRecommendationsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getReturnURL",
      [ ["in", "GetReturnURLRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetReturnURLRequest"], true],
        ["out", "GetReturnURLResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetReturnURLResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getRuName",
      [ ["in", "GetRuNameRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetRuNameRequest"], true],
        ["out", "GetRuNameResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetRuNameResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getSearchResults",
      [ ["in", "GetSearchResultsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSearchResultsRequest"], true],
        ["out", "GetSearchResultsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSearchResultsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getSellerEvents",
      [ ["in", "GetSellerEventsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerEventsRequest"], true],
        ["out", "GetSellerEventsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerEventsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getSellerList",
      [ ["in", "GetSellerListRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerListRequest"], true],
        ["out", "GetSellerListResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerListResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getSellerPayments",
      [ ["in", "GetSellerPaymentsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerPaymentsRequest"], true],
        ["out", "GetSellerPaymentsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerPaymentsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getSellerTransactions",
      [ ["in", "GetSellerTransactionsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerTransactionsRequest"], true],
        ["out", "GetSellerTransactionsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSellerTransactionsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getStore",
      [ ["in", "GetStoreRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStoreRequest"], true],
        ["out", "GetStoreResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStoreResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getStoreCustomPage",
      [ ["in", "GetStoreCustomPageRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStoreCustomPageRequest"], true],
        ["out", "GetStoreCustomPageResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStoreCustomPageResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getStoreOptions",
      [ ["in", "GetStoreOptionsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStoreOptionsRequest"], true],
        ["out", "GetStoreOptionsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStoreOptionsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getStorePreferences",
      [ ["in", "GetStorePreferencesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStorePreferencesRequest"], true],
        ["out", "GetStorePreferencesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetStorePreferencesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getSuggestedCategories",
      [ ["in", "GetSuggestedCategoriesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSuggestedCategoriesRequest"], true],
        ["out", "GetSuggestedCategoriesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetSuggestedCategoriesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getTaxTable",
      [ ["in", "GetTaxTableRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetTaxTableRequest"], true],
        ["out", "GetTaxTableResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetTaxTableResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getUser",
      [ ["in", "GetUserRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetUserRequest"], true],
        ["out", "GetUserResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetUserResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getUserDisputes",
      [ ["in", "GetUserDisputesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetUserDisputesRequest"], true],
        ["out", "GetUserDisputesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetUserDisputesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getUserPreferences",
      [ ["in", "GetUserPreferencesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetUserPreferencesRequest"], true],
        ["out", "GetUserPreferencesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetUserPreferencesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getWantItNowPost",
      [ ["in", "GetWantItNowPostRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetWantItNowPostRequest"], true],
        ["out", "GetWantItNowPostResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetWantItNowPostResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "getWantItNowSearchResults",
      [ ["in", "GetWantItNowSearchResultsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetWantItNowSearchResultsRequest"], true],
        ["out", "GetWantItNowSearchResultsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GetWantItNowSearchResultsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "geteBayDetails",
      [ ["in", "GeteBayDetailsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GeteBayDetailsRequest"], true],
        ["out", "GeteBayDetailsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GeteBayDetailsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "geteBayOfficialTime",
      [ ["in", "GeteBayOfficialTimeRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GeteBayOfficialTimeRequest"], true],
        ["out", "GeteBayOfficialTimeResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "GeteBayOfficialTimeResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "issueRefund",
      [ ["in", "IssueRefundRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "IssueRefundRequest"], true],
        ["out", "IssueRefundResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "IssueRefundResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "leaveFeedback",
      [ ["in", "LeaveFeedbackRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "LeaveFeedbackRequest"], true],
        ["out", "LeaveFeedbackResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "LeaveFeedbackResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "relistItem",
      [ ["in", "RelistItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RelistItemRequest"], true],
        ["out", "RelistItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RelistItemResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "removeFromWatchList",
      [ ["in", "RemoveFromWatchListRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RemoveFromWatchListRequest"], true],
        ["out", "RemoveFromWatchListResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RemoveFromWatchListResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "respondToBestOffer",
      [ ["in", "RespondToBestOfferRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RespondToBestOfferRequest"], true],
        ["out", "RespondToBestOfferResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RespondToBestOfferResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "respondToFeedback",
      [ ["in", "RespondToFeedbackRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RespondToFeedbackRequest"], true],
        ["out", "RespondToFeedbackResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RespondToFeedbackResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "respondToWantItNowPost",
      [ ["in", "RespondToWantItNowPostRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RespondToWantItNowPostRequest"], true],
        ["out", "RespondToWantItNowPostResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "RespondToWantItNowPostResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "reviseCheckoutStatus",
      [ ["in", "ReviseCheckoutStatusRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseCheckoutStatusRequest"], true],
        ["out", "ReviseCheckoutStatusResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseCheckoutStatusResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "reviseItem",
      [ ["in", "ReviseItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseItemRequest"], true],
        ["out", "ReviseItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseItemResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "reviseMyMessages",
      [ ["in", "ReviseMyMessagesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseMyMessagesRequest"], true],
        ["out", "ReviseMyMessagesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseMyMessagesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "reviseMyMessagesFolders",
      [ ["in", "ReviseMyMessagesFoldersRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseMyMessagesFoldersRequest"], true],
        ["out", "ReviseMyMessagesFoldersResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ReviseMyMessagesFoldersResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "sellerReverseDispute",
      [ ["in", "SellerReverseDisputeRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SellerReverseDisputeRequest"], true],
        ["out", "SellerReverseDisputeResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SellerReverseDisputeResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "sendInvoice",
      [ ["in", "SendInvoiceRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SendInvoiceRequest"], true],
        ["out", "SendInvoiceResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SendInvoiceResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "setNotificationPreferences",
      [ ["in", "SetNotificationPreferencesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetNotificationPreferencesRequest"], true],
        ["out", "SetNotificationPreferencesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetNotificationPreferencesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "setPictureManagerDetails",
      [ ["in", "SetPictureManagerDetailsRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetPictureManagerDetailsRequest"], true],
        ["out", "SetPictureManagerDetailsResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetPictureManagerDetailsResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "setPromotionRules",
      [ ["in", "SetPromotionRulesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetPromotionRulesRequest"], true],
        ["out", "SetPromotionRulesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetPromotionRulesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "setReturnURL",
      [ ["in", "SetReturnURLRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetReturnURLRequest"], true],
        ["out", "SetReturnURLResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetReturnURLResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "setStore",
      [ ["in", "SetStoreRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetStoreRequest"], true],
        ["out", "SetStoreResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetStoreResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "setStoreCustomPage",
      [ ["in", "SetStoreCustomPageRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetStoreCustomPageRequest"], true],
        ["out", "SetStoreCustomPageResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetStoreCustomPageResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "setStorePreferences",
      [ ["in", "SetStorePreferencesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetStorePreferencesRequest"], true],
        ["out", "SetStorePreferencesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetStorePreferencesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "setTaxTable",
      [ ["in", "SetTaxTableRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetTaxTableRequest"], true],
        ["out", "SetTaxTableResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetTaxTableResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "setUserNotes",
      [ ["in", "SetUserNotesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetUserNotesRequest"], true],
        ["out", "SetUserNotesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetUserNotesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "setUserPreferences",
      [ ["in", "SetUserPreferencesRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetUserPreferencesRequest"], true],
        ["out", "SetUserPreferencesResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "SetUserPreferencesResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "validateTestUserRegistration",
      [ ["in", "ValidateTestUserRegistrationRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ValidateTestUserRegistrationRequest"], true],
        ["out", "ValidateTestUserRegistrationResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "ValidateTestUserRegistrationResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "verifyAddItem",
      [ ["in", "VerifyAddItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "VerifyAddItemRequest"], true],
        ["out", "VerifyAddItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "VerifyAddItemResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "verifyAddSecondChanceItem",
      [ ["in", "VerifyAddSecondChanceItemRequest", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "VerifyAddSecondChanceItemRequest"], true],
        ["out", "VerifyAddSecondChanceItemResponse", ["::SOAP::SOAPElement", "urn:ebay:apis:eBLBaseComponents", "VerifyAddSecondChanceItemResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = MappingRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end

